/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Patient = IDL.Record({
  'age' : IDL.Nat,
  'patientId' : IDL.Text,
  'name' : IDL.Text,
  'gender' : IDL.Text,
});
export const TestSession = IDL.Record({
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
  'languageSelected' : IDL.Text,
  'patientId' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllTestSessions' : IDL.Func([], [IDL.Vec(TestSession)], ['query']),
  'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
  'getSessionsByPatientId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TestSession)],
      ['query'],
    ),
  'savePatient' : IDL.Func([Patient], [], []),
  'saveTestSession' : IDL.Func([TestSession], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Patient = IDL.Record({
    'age' : IDL.Nat,
    'patientId' : IDL.Text,
    'name' : IDL.Text,
    'gender' : IDL.Text,
  });
  const TestSession = IDL.Record({
    'startTime' : IDL.Nat,
    'endTime' : IDL.Nat,
    'languageSelected' : IDL.Text,
    'patientId' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllTestSessions' : IDL.Func([], [IDL.Vec(TestSession)], ['query']),
    'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
    'getSessionsByPatientId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TestSession)],
        ['query'],
      ),
    'savePatient' : IDL.Func([Patient], [], []),
    'saveTestSession' : IDL.Func([TestSession], [], []),
  });
};

export const init = ({ IDL }) => { return []; };